server:
  port: ${SERVER_PORT:7504}

spring:
  application:
    name: CustomerAccountService

  datasource:
    initialization-mode: always
    url: jdbc:mysql://cas-mysql:3306/customer-account?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
          format_sql: true

  liquibase:
    change-log: classpath:mysql/changelog/changelog-master.xml

  swagger-ui:
    path: /swagger-ui.html

  doc:
    api-docs:
      path: /v3/api-docs

  info:
    title: "Customer Account Service"
    description: "Customer Account Service API"
    version: "1.0.0"

logging:
  level:
    customer: DEBUG
  org:
    hibernate:
      type:
        descriptor:
          sql: TRACE

